language: node_js
node_js:
- 12.16.2
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: u9peDfgh7BbtYHQso1ltOgDL4ZI+qCkK/dEWX4WarLmIcg8i/9wyBXiGzRsc7BomlvaPmrKWMCZZ4Ne0YTJRnM/EOuEdqIaaNHGKCyTQSquRTycSefvdTv+f7xvVD+hakf55cOepcS0fsr3WtTrPsuso7CSbUsnK8PHzWQR032g7pwM1j+lf1depLbhe+yPisbo/Nq7las2pJRADPrF2mySWQ/e8k4ZoCBdxQEHU4N6q2elxNOq0HcBCoc6hyhlvqr8mwsBlHZ9XrxNrVcRD2I+2LPWPYgxGRHH5uVk7NA4T2/DvnK/alNy1nTec4KixJLhkRq9OTVziETGu5JPuJkFGM74bkx3Ii9fvO+RWIPqp/VfAZ5816JmN65IDAtiOIjG6qAYtW/5YVa5z9eJKPU3Zy2CWGZB/wVDt9Sx5lRYD6C6tia6aHlV+0zNO/XeU/XW2K8zUZaKp5t+VWdPAqgwsavJ+U6q5v59xOfR87cWSCIWkj+0Z2O/EVk8vgY3TcSC68zHNqO0naBqI4HqJ1+dghZldRE75MZPQebVoR8hy8GQKZwe0Q5poI1gZGBYVDSRSj1QLcm78h0yEefbhJpULd434EyeRxHC4KeCyM/nOAD0xs5Q1msbpF1ZKjQpJB3eUyeNDVgQYLCcV8Cf176gsa51VLpr00Qp7DwhNucA=
  app:
    master: my-node
    dev: node-hello-world-staging

