language: node_js
node_js:
- 12.16.2
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: CI03Eu1ytBjQb+ZovJ85d5tPJ3gdBe5zynYZTitfNJIa4qVrhoH9C6OsPEcw4LIajjvVfSvQ9SUxi8WNf5G6LkLPteG6hYVKdI3mRDD4spAwOSJn4W2huOaJUIevl/nBnWNfdRNnGM6YRL17ZRh/qccT5C2vcNn3+lMB00pOZdjh2FEtM+LdOyOHdLF8bLpBzwU9Pj+bB98sp5syNFBcQRamHAhqk3jfdySLnWHtTv67AqiJ9ESYqd685aWqELYwA35ob9KfoIRs/EO6NQciXTiwVFjGtq5RaydHE3n20ZRkOIIyVbOxu+p6BQA1Zp05nur40YSd7NTbBeVGIm8qKwJ16f456Vjbw+IWGNsfhWWiliXuzAF4pFEBOeDLqotQQjBS12xgZIE+hQVahUOIj03kQplnyyGV/b4kaF9qZBmsQfQ8s3vIR/HvkSU3SlRXPI7jDYuJ7DR+8Ok0RcHD9dfqRz+KQ9WT0yCPWLY1FAMlrk+20uv+nsAeVkRtkz22V0sNku8JvZpxXJn4Gs0m/LWjev71UeM58xILqwH5OsXtmZlWH7UMRa0whdDFsB8sMLA2pvx57Fn58R0UAP17GlSpoNTsY9Lv2kZuYPyV2HNYjhephCNW6I6HkPKpZJVpXe3qGWvjIshDlYWSMqWr1epaqksBGyG5wu+KaGDlmQA=
  app:
    master: my-node
    dev: node-hello-world-staging

