apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-svc
spec:
  selector:
    app: nginx-1
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
